/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppHistoryRouteImport } from './routes/_app.history'
import { Route as AppResumesIndexRouteImport } from './routes/_app.resumes.index'
import { Route as AppJobsIndexRouteImport } from './routes/_app.jobs.index'
import { Route as AppResumesNewRouteImport } from './routes/_app.resumes.new'
import { Route as AppResumesIdRouteImport } from './routes/_app.resumes.$id'
import { Route as AppJobsNewRouteImport } from './routes/_app.jobs.new'
import { Route as AppJobsIdRouteImport } from './routes/_app.jobs.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppResumesIndexRoute = AppResumesIndexRouteImport.update({
  id: '/resumes/',
  path: '/resumes/',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsIndexRoute = AppJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => AppRoute,
} as any)
const AppResumesNewRoute = AppResumesNewRouteImport.update({
  id: '/resumes/new',
  path: '/resumes/new',
  getParentRoute: () => AppRoute,
} as any)
const AppResumesIdRoute = AppResumesIdRouteImport.update({
  id: '/resumes/$id',
  path: '/resumes/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsNewRoute = AppJobsNewRouteImport.update({
  id: '/jobs/new',
  path: '/jobs/new',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsIdRoute = AppJobsIdRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/history': typeof AppHistoryRoute
  '/profile': typeof AppProfileRoute
  '/jobs/$id': typeof AppJobsIdRoute
  '/jobs/new': typeof AppJobsNewRoute
  '/resumes/$id': typeof AppResumesIdRoute
  '/resumes/new': typeof AppResumesNewRoute
  '/jobs/': typeof AppJobsIndexRoute
  '/resumes/': typeof AppResumesIndexRoute
}
export interface FileRoutesByTo {
  '/history': typeof AppHistoryRoute
  '/profile': typeof AppProfileRoute
  '/': typeof AppIndexRoute
  '/jobs/$id': typeof AppJobsIdRoute
  '/jobs/new': typeof AppJobsNewRoute
  '/resumes/$id': typeof AppResumesIdRoute
  '/resumes/new': typeof AppResumesNewRoute
  '/jobs': typeof AppJobsIndexRoute
  '/resumes': typeof AppResumesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/history': typeof AppHistoryRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/': typeof AppIndexRoute
  '/_app/jobs/$id': typeof AppJobsIdRoute
  '/_app/jobs/new': typeof AppJobsNewRoute
  '/_app/resumes/$id': typeof AppResumesIdRoute
  '/_app/resumes/new': typeof AppResumesNewRoute
  '/_app/jobs/': typeof AppJobsIndexRoute
  '/_app/resumes/': typeof AppResumesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/profile'
    | '/jobs/$id'
    | '/jobs/new'
    | '/resumes/$id'
    | '/resumes/new'
    | '/jobs/'
    | '/resumes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/history'
    | '/profile'
    | '/'
    | '/jobs/$id'
    | '/jobs/new'
    | '/resumes/$id'
    | '/resumes/new'
    | '/jobs'
    | '/resumes'
  id:
    | '__root__'
    | '/_app'
    | '/_app/history'
    | '/_app/profile'
    | '/_app/'
    | '/_app/jobs/$id'
    | '/_app/jobs/new'
    | '/_app/resumes/$id'
    | '/_app/resumes/new'
    | '/_app/jobs/'
    | '/_app/resumes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resumes/': {
      id: '/_app/resumes/'
      path: '/resumes'
      fullPath: '/resumes/'
      preLoaderRoute: typeof AppResumesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs/': {
      id: '/_app/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof AppJobsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resumes/new': {
      id: '/_app/resumes/new'
      path: '/resumes/new'
      fullPath: '/resumes/new'
      preLoaderRoute: typeof AppResumesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resumes/$id': {
      id: '/_app/resumes/$id'
      path: '/resumes/$id'
      fullPath: '/resumes/$id'
      preLoaderRoute: typeof AppResumesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs/new': {
      id: '/_app/jobs/new'
      path: '/jobs/new'
      fullPath: '/jobs/new'
      preLoaderRoute: typeof AppJobsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs/$id': {
      id: '/_app/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof AppJobsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppHistoryRoute: typeof AppHistoryRoute
  AppProfileRoute: typeof AppProfileRoute
  AppIndexRoute: typeof AppIndexRoute
  AppJobsIdRoute: typeof AppJobsIdRoute
  AppJobsNewRoute: typeof AppJobsNewRoute
  AppResumesIdRoute: typeof AppResumesIdRoute
  AppResumesNewRoute: typeof AppResumesNewRoute
  AppJobsIndexRoute: typeof AppJobsIndexRoute
  AppResumesIndexRoute: typeof AppResumesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHistoryRoute: AppHistoryRoute,
  AppProfileRoute: AppProfileRoute,
  AppIndexRoute: AppIndexRoute,
  AppJobsIdRoute: AppJobsIdRoute,
  AppJobsNewRoute: AppJobsNewRoute,
  AppResumesIdRoute: AppResumesIdRoute,
  AppResumesNewRoute: AppResumesNewRoute,
  AppJobsIndexRoute: AppJobsIndexRoute,
  AppResumesIndexRoute: AppResumesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
